import AppLayout from '@/components/AppLayout';
import HeaderLayout from '@/components/HeaderLayout';
import Header from '@/components/HeaderLayout';
import styles from '@/styles/Home.module.css';
import { Inter } from '@next/font/google';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { ReactElement, useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] });

Home.getLayout = function getLayout(page: ReactElement) {
    return (
        <AppLayout>
            <HeaderLayout />
            {page}
        </AppLayout>
    );
};

export default function Home() {
    const router = useRouter();

    let timer: null | NodeJS.Timeout;
    const handleWheel = (e: WheelEvent) => {
        if (timer) return;
        timer = setTimeout(function () {
            timer = null;
            let hasScroll = window.innerHeight == document.body.offsetHeight ? true : false;
            if (!hasScroll) {
                if (e.deltaY > 0) {
                    router.push('/about');
                }
            } else {
                if (
                    window.innerHeight + window.scrollY >= document.body.offsetHeight &&
                    e.deltaY > 0
                ) {
                    router.push('/about');
                }
            }
        }, 500);
    };

    useEffect(() => {
        window.addEventListener('wheel', handleWheel);
        return () => {
            window.removeEventListener('wheel', handleWheel);
        };
    }, []);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div className={styles.title}>Hello!</div>
                <div>
                    <div className={styles.desc}>I'm Miyoung.</div>
                    <div className={styles.desc}>I'm a Full Stack Web Developer!</div>
                </div>
            </main>
        </>
    );
}
